apiVersion: moodlecontroller.kubeplus/v1
kind: Moodle
metadata:
  name: moodle1-dan
  namespace: namespace1
  annotations:
    backup-volume: /opt/moodledata
spec:
  plugins: ["profilecohort"]
  # <namespace>.<kind>.<instanceName>.<outputVariable>
  # mySQLServiceName: cluster1-mysql-master
  mySQLServiceName: Fn::ImportValue(namespace1.MysqlCluster.cluster1.service)
  mySQLUserName: root
  mySQLUserPassword: cluster1-secret.ROOT_PASSWORD
  moodleAdminEmail: test@test.com
